C18/18-4/pizzas/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza')
]

C18/18-4/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls', namespace='pizzas'))
]

C18/18-5/meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meal_plans.urls', namespace='meal_plans'))
]

C18/18-5/meal_plans/urls.py
from django.urls import include, path, re_path
from . import views

app_name = 'meal_plans'

urlpatterns = [
    path('', views.index, name='index')
]

C18/instabook/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

C18/18-4/pizzas/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.PROTECT)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

C18/18-5/meal_plans/models.py
from django.db import models

# Create your models here.

C18/instabooks/models.py
from django.db import models

# Database queries for Django 2.0
# https://docs.djangoproject.com/en/2.0/topics/db/queries/

C18/18-4/pizzas/views.py
from django.shortcuts import render
from .models import Pizza, Topping


def index(request):
    return render(request, 'pizzas/index.html')


def pizzas(request):
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    context = {
        'pizza': pizza,
        'toppings': toppings,
    }
    return render(request, 'pizzas/pizza.html', context)

C18/18-5/meal_plans/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'meal_plans/index.html')

C18/instabooks/views.py
from django.shortcuts import render

# Create your views here.

C18/18-4/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Home</a> -
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock %}

C18/18-4/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
<p>
    Pizzas are on sale!
</p>
{% endblock %}

C18/18-4/pizzas/templates/pizzas/pizza.html
{% extends 'pizzas/base.html' %}

{% block content %}
    <p>Pizza: {{ pizza }}</p>
    <ul>
        {% for topping in toppings %}
            <li>{{ topping.name }}</li>
        {% empty %}
            <li>
                There is no topping in this pizza.
            </li>
        {% endfor %}
    </ul>
{% endblock %}

C18/18-4/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
    <p>Pizzas</p>

    <ul>
        {% for pizza in pizzas %}
            <li>
                <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name }}</a>
            </li>
        {% empty %}
            <li>
                Sorry, no pizza is on sale.
            </li>
        {% endfor %}
    </ul>
{% endblock %}

C18/18-5/meal_plans/templates/meal_plans/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MEAL PLANNER</title>
</head>
<body>

    <p>Meal plans</p>

    <p>Here you can plan your meal.</p>
</body>
</html>

<!-- Django 2.0 template documentation for 18-7 -->
<!-- https://docs.djangoproject.com/en/2.0/ref/templates/language/ -->