C19/19-1_Blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),

]

C19/19-1_Blog/blogs/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('blog/<int:blog_id>', views.blog, name='blog'),
    path('blog/new_blog', views.new_blog, name='new_blog'),
    path('blog/edit_blog/<int:blog_id>', views.edit_blog, name='edit_blog'),
]

C19/19-1_Blog/users/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),

]

C19/19-1_Blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class BlogPost(models.Model):

    title = models.CharField(max_length=50)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + ' ' + self.date_added + '\n\n' + self.text

C19/19-1_Blog/users/models.py
from django.db import models

# Create your models here.

C19/19-1_Blog/blogs/forms.py
from django import forms
from .models import BlogPost


class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']

C19/19-1_Blog/blogs/views.py
from django.shortcuts import render
from .models import BlogPost
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import BlogForm
from django.contrib.auth.decorators import login_required
from .auth import check_blog_author


def index(request):
    blogs = BlogPost.objects.order_by('-date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/index.html', context)


@login_required
def new_blog(request):

    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.save()
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


def blog(request, blog_id):
    blog = BlogPost.objects.get(id=blog_id)
    context = {'blog': blog}
    return render(request, 'blogs/blog.html', context)


@login_required
def edit_blog(request, blog_id):
    blog = BlogPost.objects.get(id=blog_id)

    if request.method != 'POST':
        if check_blog_author(request, blog_id):
            form = BlogForm(instance=blog)
        else:
            raise Http404
    else:
        form = BlogForm(instance=blog, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:blog', args=[blog_id]))

    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)

C19/19-1_Blog/users/views.py
from django.shortcuts import render
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):

    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(request,
                                              username=new_user.username,
                                              password=request.POST[
                                                  'password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

C19/19-1_Blog/blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title> Blog </title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blogs:index' %}">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href=
                                    "{% url 'blogs:new_blog' %}">New Blog</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <span class="navbar-text">
                            Hello, {{ user.username }}
                        </span>
                        <li class="nav-item">
                            <a href="{% url 'users:logout' %}" class="btn
                        btn-light mx-2">Log out</a>
                        </li>
                    {% else %}
                        {% block log-btns %}
                            <li class="nav-item">
                                <a href="{% url 'users:register' %}"
                                   class="btn btn-light ">Register</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'users:login' %}" class="btn
                                btn-primary mx-2">Log in</a>
                            </li>
                        {% endblock %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="page-header my-5">
            {% block header %}{% endblock %}
        </div>
        <div class="my-4">
            {% block content %}{% endblock %}
        </div>
    </div>

    <nav class="navbar fixed-bottom navbar-dark bg-dark">
        <span class="navbar-text mx-auto">
             Copyright &copy; 2018 <a href="https://triplez.cn">TripleZ</a>
        </span>
    </nav>
</body>
</html>

C19/19-1_Blog/blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block header %}

    <div class="row">
        <div class="col">
            <h2 class="">{{ blog.title }}</h2>
        </div>
        {% if user.is_authenticated %}
        <div class="col-md-auto mx-5">
            <a class="btn btn-outline-info" href=
                    "{% url 'blogs:edit_blog' blog.id %}">Edit blog</a>
        </div>
        {% endif %}
    </div>


    <h5 class="my-auto">Publish time:
        {{ blog.date_added|date:'M d, Y H:i' }}</h5>

{% endblock %}

{% block content %}

    <div class="">
        <p>{{ blog.text }}</p>
    </div>

{% endblock %}

C19/19-1_Blog/blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Edit Blog</h2>
{% endblock %}

{% block content %}

    <form class="form" action="{% url 'blogs:edit_blog' blog.id %}"
          method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button name="submit" class="btn btn-outline-success
        btn-block">RePost</button>
    </form>

{% endblock %}

C19/19-1_Blog/blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block header %}

    <div class="list-group list-group-flush my-3">
        {% for blog in blogs %}
            <a class="list-group-item list-group-item-action" href=
                    "{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>
        {% empty %}
            <a class="list-group-item
            list-group-item-danger list-group-item-action
            disabled" >There is o blog post.</a>
        {% endfor %}
    </div>

{% endblock %}

{% block content %}

{% endblock %}

C19/19-1_Blog/blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block header %}

    <h2>New Blog</h2>

{% endblock %}

{% block content %}

    <div class="row">
        <div class="col">
            <form action="{% url 'blogs:new_blog' %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button name="submit" class="btn
                btn-outline-success btn-block">Post</button>
            </form>

        </div>
    </div>


{% endblock %}

C19/19-1_Blog/users/templates/users/login.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block log-btns %}{% endblock %}

{% block content %}

    <div class="row my-5">
        <div class="mx-auto col-md-4">
            <form class="form" method="POST" action=
                    "{% url 'users:login' %}">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button name="submit" class="btn btn-primary
                btn-block">Log
                    in</button>
                <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
            </form>
            <a href="{% url 'users:register' %}" class="btn
            btn-outline-success btn-block my-2">Register</a>

        </div>

    </div>
{% endblock %}

C19/19-1_Blog/users/templates/users/register.html
{% extends 'blogs/base.html' %}
{% load bootstrap4 %}

{% block log-btns %}{% endblock %}

{% block content %}

    <div class="row my-5">
        <div class="mx-auto col-md-6">
            <form method="POST" action="{% url 'users:register' %}">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button name="submit" class="btn
                btn-outline-success">register</button>
            </form>
        </div>
    </div>

{% endblock %}