learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^users/', include('users.urls', namespace='users')),
    re_path(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_log/learning_logs/urls.py
from django.urls import include, path, re_path

from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page
    re_path(r'^$', views.index, name='index'),
    # Show all the topics
    re_path(r'^topics/$', views.topics, name='topics'),
    # Specific topic
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    # New topic
    re_path(r'^new_topic/$', views.new_topic, name='new_topic'),
    # New entry
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry,
            name='new_entry'),
    # Edit entry
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
            name='edit_entry'),
]

learning_log/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

app_name = 'users'

urlpatterns = [
    # Log in page
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),

]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """User learning topic"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    public = models.BooleanField()

    def __str__(self):
        """Use string to present """
        return self.text


class Entry(models.Model):
    """Learning specific knowledge"""
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        # 18-2
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'public']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Topic, Entry
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from .auth import check_topic_owener
from django.db.models import Q


def index(request):
    """ Main page of learning logs """
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Show all the topics"""
    topics = Topic.objects.filter(Q(owner=request.user) | Q(
        public=True)).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show specific topic"""
    # topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    if not check_topic_owener(request, topic_id):
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)



@login_required
def new_topic(request):
    """Create a new topic"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Create a new entry"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 19-4
        if check_topic_owener(request, topic_id):
            form = EntryForm()
        else:
            raise Http404
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit a entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # if topic.owner != request.user:
    if not check_topic_owener(request, topic.id):
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_log/users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Log out"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()

            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)

            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                    Learning Log</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <a>Hello, {{ user.username }}.</a>
                        </li>
                        <li>
                            <a href="{% url 'users:logout' %}">log out</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'users:register' %}">register</a>
                        </li>
                        <li>
                            <a href="{% url 'users:login' %}">login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="page-header">
            {% block header %}
            {% endblock %}
        </div>

        <div>
            {% block content %}
            {% endblock %}
        </div>

    </div>
</body>

</html>

learning_log/learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}

    <h3>
        <a href:"{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3>

    <h2>Edit entry</h2>

{% endblock %}

{% block content %}

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST"
            class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button action="submit" class="btn btn-primary">save
            changes</button>
        {% endbuttons %}
    </form>


{% endblock %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}

    <div class="jumbotron">
        <h1>Track your learning</h1>
    </div>
{% endblock %}

{% block content %}

    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own Learning Log, and list the topic you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make aa entry
        summarizing what you've learned.
    </h2>

{% endblock %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h2>
{% endblock %}

{% block content %}

    <h3>Add a new entry: </h3>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST"
          class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add entry</button>
        {% endbuttons%}
    </form>

{% endblock %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock %}

{% block content %}

    <form action="{% url 'learning_logs:new_topic' %}" method="POST"
          class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    </form>

{% endblock %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h2>{{ topic }}</h2>

    {% if user == topic.owner %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">
            Add a new entry
        </a>
    </p>

    {% else %}
        <p>
            Topic owner: {{ topic.owner }}
        </p>

    {% endif %}
{% endblock %}

{% block content %}

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    {% if user == topic.owner %}
                    <small>
                        <a href="
{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
                    </small>
                    {% endif %}
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}

{% endblock %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_logs:topic' topic.id %}">
                        {{ topic }}
                    </a>
                </h3>
            </li>
        {% empty %}
            <li>No topic have been added yet.</li>
        {% endfor %}
    </ul>

    <h3>
        <a href="{% url 'learning_logs:new_topic' %}"> Add a new topic</a>
    </h3>

{% endblock %}

learning_log/users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Log in to your account</h2>
{% endblock %}

{% block content %}

{#    {% if form.errors %}#}
{#        <p>Your username and password didn't match. Please try again.</p>#}
{#    {% endif %}#}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

{#        {{ form.as_p }}#}
        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}

        <input type="hidden" name="next" value="{%  url 'learning_logs:index' %}"/>
    </form>

{% endblock %}

learning_log/users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block content %}

    <form action="{% url 'users:register' %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value=
                "{% url 'learning_logs:index' %}"/>

    </form>
{% endblock %}